# Generated by Django 4.2 on 2024-01-01 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='网站名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='网站编码')),
                ('website_type', models.CharField(choices=[('government', '政府采购网'), ('enterprise', '企业招标平台'), ('construction', '工程建设平台'), ('medical', '医疗器械采购'), ('education', '教育采购平台'), ('other', '其他平台')], default='other', max_length=20, verbose_name='网站类型')),
                ('base_url', models.URLField(max_length=500, verbose_name='基础URL')),
                ('list_url_pattern', models.CharField(blank=True, help_text='支持变量: {page}, {keyword}, {category}', max_length=500, null=True, verbose_name='列表URL模式')),
                ('search_url_pattern', models.CharField(blank=True, help_text='支持变量: {keyword}, {page}', max_length=500, null=True, verbose_name='搜索URL模式')),
                ('selectors', models.JSONField(blank=True, default=dict, verbose_name='选择器配置')),
                ('pagination_config', models.JSONField(blank=True, default=dict, verbose_name='分页配置')),
                ('request_config', models.JSONField(blank=True, default=dict, verbose_name='请求配置')),
                ('requires_javascript', models.BooleanField(default=False, verbose_name='需要JS渲染')),
                ('requires_login', models.BooleanField(default=False, verbose_name='需要登录')),
                ('login_config', models.JSONField(blank=True, default=dict, verbose_name='登录配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '网站模板',
                'verbose_name_plural': '网站模板',
                'db_table': 'website_templates',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='会话名称')),
                ('target_url', models.URLField(max_length=1000, verbose_name='目标URL')),
                ('crawl_type', models.CharField(default='list', help_text='list: 列表采集, search: 搜索采集, detail: 详情采集', max_length=50, verbose_name='采集类型')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='搜索关键词')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='采集参数')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '执行失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('total_pages', models.IntegerField(default=0, verbose_name='总页数')),
                ('current_page', models.IntegerField(default=0, verbose_name='当前页')),
                ('result_count', models.IntegerField(default=0, verbose_name='结果数量')),
                ('error_count', models.IntegerField(default=0, verbose_name='错误数量')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.IntegerField(default=0, verbose_name='耗时(秒)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('website_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_sessions', to='crawler.websitetemplate', verbose_name='网站模板')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '采集会话',
                'verbose_name_plural': '采集会话',
                'db_table': 'crawl_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='标题')),
                ('source_url', models.URLField(max_length=1000, verbose_name='来源URL')),
                ('detail_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='详情URL')),
                ('publish_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='发布日期')),
                ('deadline_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='地区')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='类别')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='行业')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='预算金额')),
                ('project_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目编号')),
                ('purchaser_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='采购人名称')),
                ('purchaser_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='采购人联系人')),
                ('purchaser_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='采购人电话')),
                ('agency_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='代理机构名称')),
                ('agency_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='代理机构联系人')),
                ('agency_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='代理机构电话')),
                ('description', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='技术要求')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('extracted_fields', models.JSONField(blank=True, default=dict, verbose_name='提取字段')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processed', '已处理'), ('matched', '已匹配'), ('ignored', '已忽略')], default='pending', max_length=20, verbose_name='状态')),
                ('matched_companies', models.JSONField(blank=True, default=list, verbose_name='匹配企业')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='crawler.crawlsession', verbose_name='采集会话')),
            ],
            options={
                'verbose_name': '采集结果',
                'verbose_name_plural': '采集结果',
                'db_table': 'crawl_results',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR')], default='info', max_length=10, verbose_name='日志级别')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='相关URL')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crawler.crawlsession', verbose_name='采集会话')),
            ],
            options={
                'verbose_name': '采集日志',
                'verbose_name_plural': '采集日志',
                'db_table': 'crawl_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
