# Generated by Django 5.2.12 on 2026-03-19 02:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidProjectTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_title', models.CharField(max_length=500, verbose_name='项目标题')),
                ('tender_url', models.URLField(max_length=1000, verbose_name='项目链接')),
                ('tender_source', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目来源')),
                ('bid_date', models.DateField(verbose_name='投标日期')),
                ('bid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='投标金额')),
                ('bid_company', models.CharField(blank=True, max_length=300, null=True, verbose_name='投标单位')),
                ('tracking_status', models.CharField(choices=[('tracking', '跟踪中'), ('won', '已中标'), ('lost', '未中标'), ('cancelled', '已取消'), ('expired', '已过期')], default='tracking', max_length=20, verbose_name='跟踪状态')),
                ('result_announce_date', models.DateField(blank=True, null=True, verbose_name='结果公告日期')),
                ('winner_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='中标单位')),
                ('winner_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='中标金额')),
                ('our_rank', models.IntegerField(blank=True, null=True, verbose_name='我方排名')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='最后检查时间')),
                ('check_count', models.IntegerField(default=0, verbose_name='检查次数')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='已发送通知')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='通知发送时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '已投标项目跟踪',
                'verbose_name_plural': '已投标项目跟踪',
                'db_table': 'bid_project_tracking',
                'ordering': ['-bid_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('crontab', models.CharField(default='0 8 * * *', help_text='格式: 分 时 日 月 周，如 "0 8 * * *" 表示每天8点执行', max_length=100, verbose_name='Cron表达式')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('status', models.CharField(choices=[('active', '已启用'), ('paused', '已暂停'), ('deleted', '已删除')], default='active', max_length=20, verbose_name='状态')),
                ('max_pages', models.IntegerField(default=5, verbose_name='最大采集页数')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='搜索关键词')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='采集参数')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('last_result_count', models.IntegerField(default=0, verbose_name='上次采集数量')),
                ('total_result_count', models.IntegerField(default=0, verbose_name='累计采集数量')),
                ('run_count', models.IntegerField(default=0, verbose_name='执行次数')),
                ('error_count', models.IntegerField(default=0, verbose_name='错误次数')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='上次错误信息')),
                ('auto_match', models.BooleanField(default=True, help_text='采集完成后自动进行企业资质匹配', verbose_name='自动匹配企业资质')),
                ('auto_delete_unmatched', models.BooleanField(default=False, help_text='不符合企业要求的项目自动删除', verbose_name='自动删除不匹配项目')),
                ('match_threshold', models.FloatField(default=0.6, help_text='低于此阈值的视为不匹配，范围0-1', verbose_name='匹配阈值')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '采集计划',
                'verbose_name_plural': '采集计划',
                'db_table': 'crawl_schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlScheduleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], default='running', max_length=20, verbose_name='状态')),
                ('result_count', models.IntegerField(default=0, verbose_name='采集数量')),
                ('matched_count', models.IntegerField(default=0, verbose_name='匹配数量')),
                ('deleted_count', models.IntegerField(default=0, verbose_name='删除数量')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='详细信息')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.IntegerField(default=0, verbose_name='耗时(秒)')),
            ],
            options={
                'verbose_name': '采集计划日志',
                'verbose_name_plural': '采集计划日志',
                'db_table': 'crawl_schedule_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseVectorIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_id', models.IntegerField(unique=True, verbose_name='企业ID')),
                ('enterprise_name', models.CharField(max_length=300, verbose_name='企业名称')),
                ('vector_text', models.TextField(help_text='用于向量化的文本内容', verbose_name='向量文本')),
                ('vector_status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='向量化状态')),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True, verbose_name='最后索引时间')),
                ('index_version', models.IntegerField(default=1, verbose_name='索引版本')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '企业向量索引',
                'verbose_name_plural': '企业向量索引',
                'db_table': 'enterprise_vector_index',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FailureKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, verbose_name='失败URL')),
                ('website', models.CharField(blank=True, max_length=200, null=True, verbose_name='网站')),
                ('failure_type', models.CharField(choices=[('network_error', '网络错误'), ('timeout', '超时'), ('blocked', '被封禁'), ('captcha', '验证码'), ('rate_limit', '限流'), ('parse_error', '解析错误'), ('unknown', '未知错误')], default='unknown', max_length=20, verbose_name='失败类型')),
                ('error_message', models.TextField(verbose_name='错误信息')),
                ('error_stack', models.TextField(blank=True, null=True, verbose_name='错误堆栈')),
                ('strategy_used', models.CharField(blank=True, max_length=50, null=True, verbose_name='使用的策略')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('resolution_status', models.CharField(choices=[('pending', '待解决'), ('resolved', '已解决'), ('ignored', '已忽略')], default='pending', max_length=20, verbose_name='解决状态')),
                ('resolution_method', models.CharField(blank=True, max_length=500, null=True, verbose_name='解决方法')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='解决备注')),
                ('proxy_used', models.CharField(blank=True, max_length=200, null=True, verbose_name='使用的代理')),
                ('fingerprint_used', models.JSONField(blank=True, default=dict, verbose_name='使用的指纹')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '失败知识库',
                'verbose_name_plural': '失败知识库',
                'db_table': 'failure_knowledge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='crawlresult',
            name='extracted_fields',
            field=models.JSONField(blank=True, default=dict, help_text='从页面提取的结构化字段', verbose_name='提取字段'),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='pagination_config',
            field=models.JSONField(blank=True, default=dict, help_text='分页相关配置', verbose_name='分页配置'),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='request_config',
            field=models.JSONField(blank=True, default=dict, help_text='请求头、代理等配置', verbose_name='请求配置'),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='selectors',
            field=models.JSONField(blank=True, default=dict, help_text='CSS选择器配置，用于提取数据', verbose_name='选择器配置'),
        ),
        migrations.AddIndex(
            model_name='crawlresult',
            index=models.Index(fields=['status', 'publish_date'], name='crawl_resul_status_2cc358_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlresult',
            index=models.Index(fields=['region', 'industry'], name='crawl_resul_region_be6c09_idx'),
        ),
        migrations.AddField(
            model_name='bidprojecttracking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='crawlschedule',
            name='celery_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_schedules', to='django_celery_beat.periodictask', verbose_name='Celery定时任务'),
        ),
        migrations.AddField(
            model_name='crawlschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='crawlschedule',
            name='website_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_schedules', to='crawler.websitetemplate', verbose_name='网站模板'),
        ),
        migrations.AddField(
            model_name='crawlschedulelog',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crawler.crawlschedule', verbose_name='采集计划'),
        ),
        migrations.AddField(
            model_name='crawlschedulelog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_logs', to='crawler.crawlsession', verbose_name='采集会话'),
        ),
        migrations.AddField(
            model_name='failureknowledge',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_failures', to=settings.AUTH_USER_MODEL, verbose_name='解决人'),
        ),
        migrations.AddIndex(
            model_name='bidprojecttracking',
            index=models.Index(fields=['tracking_status', 'last_checked_at'], name='bid_project_trackin_0cc085_idx'),
        ),
        migrations.AddIndex(
            model_name='failureknowledge',
            index=models.Index(fields=['failure_type', 'resolution_status'], name='failure_kno_failure_6a2e00_idx'),
        ),
        migrations.AddIndex(
            model_name='failureknowledge',
            index=models.Index(fields=['website'], name='failure_kno_website_311a84_idx'),
        ),
    ]
