# Generated by Django 5.2.12 on 2026-03-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_bidprojecttracking_crawlschedule_crawlschedulelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlschedule',
            name='crawl_mode',
            field=models.CharField(choices=[('full', '全量采集'), ('incremental', '增量采集')], default='full', help_text='全量采集：采集所有页面；增量采集：仅采集最新数据', max_length=20, verbose_name='采集模式'),
        ),
    ]
