# Generated by Django 5.2.12 on 2026-03-28 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_add_shanghai_gov_procurement_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlschedule',
            name='status',
            field=models.CharField(choices=[('active', '启用'), ('paused', '暂停'), ('deleted', '已删除')], default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='crawlschedule',
            name='website_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crawl_schedules', to='crawler.websitetemplate', verbose_name='网站模板'),
        ),
        migrations.AlterField(
            model_name='enterprisevectorindex',
            name='vector_status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('indexed', '已索引'), ('failed', '失败')], default='pending', max_length=20, verbose_name='向量化状态'),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='list_url_pattern',
            field=models.CharField(blank=True, help_text='支持变量: {page}, {keyword}, {category}, {start_date}, {end_date}', max_length=500, null=True, verbose_name='列表URL模式'),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='search_url_pattern',
            field=models.CharField(blank=True, help_text='支持变量: {keyword}, {page}, {start_date}, {end_date}', max_length=500, null=True, verbose_name='搜索URL模式'),
        ),
    ]
