# Generated by Django 5.2.12 on 2026-03-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_allow_website_template_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlschedule',
            name='enterprise_ids',
            field=models.JSONField(blank=True, default=list, help_text='选择参与资质匹配的企业ID', verbose_name='参与资质匹配的企业ID列表'),
        ),
        migrations.AddField(
            model_name='crawlschedule',
            name='exec_datetime',
            field=models.DateTimeField(blank=True, help_text='单次执行的指定时间', null=True, verbose_name='定时执行时间'),
        ),
        migrations.AddField(
            model_name='crawlschedule',
            name='regions',
            field=models.JSONField(blank=True, default=list, help_text='选择的省/市/区列表，留空则采集全国', verbose_name='采集地区'),
        ),
    ]
