# Generated by Django 5.2.12 on 2026-03-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_add_content_recognition_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlschedulelog',
            name='duration',
            field=models.FloatField(default=0.0, verbose_name='耗时(秒)'),
        ),
    ]
