# Generated by Django 4.2.16 on 2026-04-15 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_tenderproject_is_deleted_alter_crawlertask_source_and_more'),
        ('crawler', '0009_change_duration_to_float'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionWorkflow',
        ),
        migrations.RemoveField(
            model_name='datasourceverification',
            name='validated_by',
        ),
        migrations.AddField(
            model_name='crawlresult',
            name='tender_project',
            field=models.ForeignKey(blank=True, help_text='采集结果转化为正式招标项目后的关联', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_results', to='tenders.tenderproject', verbose_name='关联招标项目'),
        ),
        migrations.DeleteModel(
            name='CrawlerSourceConfig',
        ),
        migrations.DeleteModel(
            name='DataSourceVerification',
        ),
    ]
