# Generated by Django 4.2.16 on 2026-04-21 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crawler', '0010_delete_collectionworkflow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_connectivity', models.CharField(choices=[('pending', '待检查'), ('running', '检查中'), ('passed', '通过'), ('failed', '失败'), ('warning', '警告')], default='pending', max_length=20, verbose_name='网络连通性')),
                ('network_details', models.JSONField(blank=True, default=dict, verbose_name='网络检查详情')),
                ('http_status', models.CharField(choices=[('pending', '待检查'), ('running', '检查中'), ('passed', '通过'), ('failed', '失败'), ('warning', '警告')], default='pending', max_length=20, verbose_name='HTTP状态码')),
                ('http_status_code', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('http_details', models.JSONField(blank=True, default=dict, verbose_name='HTTP检查详情')),
                ('page_structure', models.CharField(choices=[('pending', '待检查'), ('running', '检查中'), ('passed', '通过'), ('failed', '失败'), ('warning', '警告')], default='pending', max_length=20, verbose_name='页面结构')),
                ('page_structure_diff', models.JSONField(blank=True, default=dict, verbose_name='页面结构差异')),
                ('page_structure_details', models.JSONField(blank=True, default=dict, verbose_name='页面结构检查详情')),
                ('anti_crawl', models.CharField(choices=[('pending', '待检查'), ('running', '检查中'), ('passed', '通过'), ('failed', '失败'), ('warning', '警告')], default='pending', max_length=20, verbose_name='反爬检测')),
                ('anti_crawl_indicators', models.JSONField(blank=True, default=dict, verbose_name='反爬指标')),
                ('anti_crawl_details', models.JSONField(blank=True, default=dict, verbose_name='反爬检查详情')),
                ('extraction_rules', models.CharField(choices=[('pending', '待检查'), ('running', '检查中'), ('passed', '通过'), ('failed', '失败'), ('warning', '警告')], default='pending', max_length=20, verbose_name='提取规则')),
                ('extraction_rules_invalid', models.JSONField(blank=True, default=list, verbose_name='失效的提取规则')),
                ('extraction_rules_details', models.JSONField(blank=True, default=dict, verbose_name='提取规则检查详情')),
                ('overall_status', models.CharField(choices=[('pending', '待检查'), ('running', '检查中'), ('passed', '通过'), ('failed', '失败'), ('warning', '警告')], default='pending', max_length=20, verbose_name='总体状态')),
                ('failure_summary', models.TextField(blank=True, default='', verbose_name='失败原因汇总')),
                ('target_url', models.URLField(max_length=1000, verbose_name='目标URL')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='检查时间')),
                ('duration', models.FloatField(default=0, verbose_name='检查耗时(秒)')),
                ('website_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_checks', to='crawler.websitetemplate', verbose_name='网站模板')),
            ],
            options={
                'verbose_name': '采集健康检查',
                'verbose_name_plural': '采集健康检查',
                'db_table': 'crawl_health_checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlOptimizationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimization_type', models.CharField(choices=[('ua_rotate', '动态调整User-Agent'), ('proxy_switch', 'IP代理切换'), ('rule_update', '更新数据提取规则'), ('captcha_handle', '验证码识别'), ('frequency_adjust', '调整请求频率'), ('strategy_downgrade', '降级采集策略'), ('cookies_refresh', '刷新Cookie')], max_length=30, verbose_name='优化类型')),
                ('description', models.TextField(verbose_name='优化描述')),
                ('parameters_before', models.JSONField(blank=True, default=dict, verbose_name='优化前参数')),
                ('parameters_after', models.JSONField(blank=True, default=dict, verbose_name='优化后参数')),
                ('is_applied', models.BooleanField(default=False, verbose_name='已应用')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='应用时间')),
                ('apply_result', models.CharField(default='pending', max_length=20, verbose_name='应用结果')),
                ('apply_details', models.TextField(blank=True, default='', verbose_name='应用详情')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('health_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_plans', to='crawler.crawlhealthcheck', verbose_name='健康检查')),
            ],
            options={
                'verbose_name': '采集优化方案',
                'verbose_name_plural': '采集优化方案',
                'db_table': 'crawl_optimization_plans',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlAssuranceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=1000, verbose_name='目标URL')),
                ('consecutive_failures', models.IntegerField(default=0, verbose_name='连续失败次数')),
                ('trigger_reason', models.TextField(blank=True, default='', verbose_name='触发原因')),
                ('status', models.CharField(choices=[('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('max_retries', '达到上限')], default='running', max_length=20, verbose_name='状态')),
                ('attempt_count', models.IntegerField(default=0, verbose_name='尝试次数')),
                ('max_attempts', models.IntegerField(default=5, verbose_name='最大尝试次数')),
                ('failure_analysis', models.TextField(blank=True, default='', verbose_name='失败原因分析')),
                ('optimization_summary', models.TextField(blank=True, default='', verbose_name='优化措施汇总')),
                ('parameters_comparison', models.JSONField(blank=True, default=dict, verbose_name='修复前后参数对比')),
                ('crawl_result_stats', models.JSONField(blank=True, default=dict, verbose_name='爬取结果统计')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='已发送通知')),
                ('notification_channels', models.JSONField(blank=True, default=list, verbose_name='通知渠道')),
                ('notification_details', models.JSONField(blank=True, default=dict, verbose_name='通知详情')),
                ('final_result', models.TextField(blank=True, default='', verbose_name='最终结果')),
                ('data_collected', models.IntegerField(default=0, verbose_name='最终采集数据量')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.FloatField(default=0, verbose_name='总耗时(秒)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('current_health_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crawler.crawlhealthcheck', verbose_name='当前健康检查')),
                ('website_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assurance_reports', to='crawler.websitetemplate', verbose_name='网站模板')),
            ],
            options={
                'verbose_name': '采集保障报告',
                'verbose_name_plural': '采集保障报告',
                'db_table': 'crawl_assurance_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='crawl_assur_status_0d57b3_idx'), models.Index(fields=['website_template', '-created_at'], name='crawl_assur_website_db1591_idx')],
            },
        ),
    ]
