# Generated by Django 4.2.7 on 2026-04-02 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_add_celery_check_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='serviceactionlog',
            new_name='service_act_service_2b35f1_idx',
            old_name='service_ac_service_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceactionlog',
            new_name='service_act_action__3a3220_idx',
            old_name='service_ac_action__idx',
        ),
        migrations.RenameIndex(
            model_name='serviceactionlog',
            new_name='service_act_started_b79876_idx',
            old_name='service_ac_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='servicealert',
            new_name='service_ale_service_8f9754_idx',
            old_name='service_al_service_idx',
        ),
        migrations.RenameIndex(
            model_name='servicealert',
            new_name='service_ale_status_2a9428_idx',
            old_name='service_al_status_idx',
        ),
        migrations.RenameIndex(
            model_name='servicealert',
            new_name='service_ale_level_defb61_idx',
            old_name='service_al_level_idx',
        ),
        migrations.RenameIndex(
            model_name='servicehealthrecord',
            new_name='service_hea_service_52c74f_idx',
            old_name='service_hea_service_idx',
        ),
        migrations.RenameIndex(
            model_name='servicehealthrecord',
            new_name='service_hea_timesta_25f047_idx',
            old_name='service_hea_timesta_idx',
        ),
        migrations.AlterField(
            model_name='serviceactionlog',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='monitor.monitoredservice'),
        ),
        migrations.AlterField(
            model_name='servicealert',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitor.monitoredservice'),
        ),
        migrations.AlterField(
            model_name='servicehealthrecord',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='monitor.monitoredservice'),
        ),
    ]
