# Generated by Django 4.2.16 on 2026-04-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_rename_service_ac_service_idx_service_act_service_2b35f1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredservice',
            name='health_check_interval',
            field=models.IntegerField(default=60, verbose_name='检查间隔(秒)'),
        ),
        migrations.AlterField(
            model_name='monitoredservice',
            name='health_check_timeout',
            field=models.IntegerField(default=3, verbose_name='检查超时(秒)'),
        ),
    ]
