# Generated by Django 5.2.12 on 2026-03-20 01:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISearchTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='搜索关键词')),
                ('document_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='目标文档类型')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='目标行业')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '执行失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度')),
                ('total_found', models.IntegerField(default=0, verbose_name='发现文档数')),
                ('saved_count', models.IntegerField(default=0, verbose_name='保存文档数')),
                ('search_config', models.JSONField(blank=True, default=dict, verbose_name='搜索配置')),
                ('search_results', models.JSONField(blank=True, default=list, verbose_name='搜索结果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'AI搜索任务',
                'verbose_name_plural': 'AI搜索任务',
                'db_table': 'ai_search_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(verbose_name='搜索内容')),
                ('search_type', models.CharField(default='semantic', help_text='semantic: 语义搜索, keyword: 关键词搜索', max_length=20, verbose_name='搜索类型')),
                ('result_count', models.IntegerField(default=0, verbose_name='结果数量')),
                ('clicked_documents', models.JSONField(blank=True, default=list, help_text='用户点击的文档ID列表', verbose_name='点击的文档')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='会话ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '文档搜索日志',
                'verbose_name_plural': '文档搜索日志',
                'db_table': 'document_search_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidDocumentLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='文档标题')),
                ('document_type', models.CharField(choices=[('bid_template', '标书范本'), ('technical_plan', '技术方案'), ('construction_plan', '施工组织设计'), ('qualification_doc', '资质文件'), ('business_doc', '商务文件'), ('price_analysis', '报价分析'), ('contract_template', '合同范本'), ('case_study', '案例资料'), ('other', '其他文档')], default='other', max_length=50, verbose_name='文档类型')),
                ('source_type', models.CharField(choices=[('upload', '用户上传'), ('ai_search', 'AI全网搜索'), ('system', '系统内置')], default='upload', max_length=20, verbose_name='来源类型')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='vectorlib/%Y/%m/', verbose_name='文档文件')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_format', models.CharField(blank=True, max_length=20, null=True, verbose_name='文件格式')),
                ('content_text', models.TextField(blank=True, help_text='提取的文本内容', null=True, verbose_name='文档内容')),
                ('content_summary', models.TextField(blank=True, null=True, verbose_name='内容摘要')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='关键词')),
                ('vector_status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('indexed', '已索引'), ('failed', '处理失败')], default='pending', max_length=20, verbose_name='向量化状态')),
                ('vector_id', models.CharField(blank=True, help_text='向量数据库中的ID', max_length=100, null=True, verbose_name='向量ID')),
                ('vector_text', models.TextField(blank=True, help_text='用于向量化的文本', null=True, verbose_name='向量文本')),
                ('source_url', models.URLField(blank=True, help_text='AI搜索来源', max_length=1000, null=True, verbose_name='来源URL')),
                ('source_website', models.CharField(blank=True, max_length=200, null=True, verbose_name='来源网站')),
                ('search_keyword', models.CharField(blank=True, help_text='AI搜索使用的关键词', max_length=200, null=True, verbose_name='搜索关键词')),
                ('project_type', models.CharField(blank=True, help_text='适用的项目类型', max_length=100, null=True, verbose_name='项目类型')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='所属行业')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='适用地区')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('view_count', models.IntegerField(default=0, verbose_name='查看次数')),
                ('use_count', models.IntegerField(default=0, help_text='在标书制作中被引用的次数', verbose_name='使用次数')),
                ('quality_score', models.IntegerField(default=0, help_text='0-100分', verbose_name='质量评分')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否已验证')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '投标文档向量库',
                'verbose_name_plural': '投标文档向量库',
                'db_table': 'bid_document_library',
                'ordering': ['-quality_score', '-use_count', '-created_at'],
                'indexes': [models.Index(fields=['document_type', 'source_type'], name='bid_documen_documen_63b92a_idx'), models.Index(fields=['vector_status'], name='bid_documen_vector__1b6d25_idx'), models.Index(fields=['industry', 'project_type'], name='bid_documen_industr_285169_idx')],
            },
        ),
    ]
