# Generated by Django 5.2.12 on 2026-03-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorlib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddocumentlibrary',
            name='vector_status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('indexed', '已索引'), ('failed', '失败')], default='pending', max_length=20, verbose_name='向量化状态'),
        ),
    ]
