# Generated by Django 5.2.12 on 2026-03-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorlib', '0002_add_reference_docs_to_generated_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisearchtask',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='aisearchtask',
            name='industry',
        ),
        migrations.AddField(
            model_name='aisearchtask',
            name='document_types',
            field=models.JSONField(blank=True, default=list, verbose_name='目标文档类型列表'),
        ),
        migrations.AddField(
            model_name='aisearchtask',
            name='industries',
            field=models.JSONField(blank=True, default=list, verbose_name='目标行业列表'),
        ),
        migrations.AddField(
            model_name='aisearchtask',
            name='keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='搜索关键词列表'),
        ),
    ]
