# Generated by Django 4.2.7 on 2026-03-23 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True, verbose_name='任务ID')),
                ('task_name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('task_type', models.CharField(choices=[('tender_scan', '招标信息扫描'), ('bid_auto_submit', '自动投标执行'), ('result_check', '中标结果检查'), ('vector_cleanup', '向量库维护'), ('system_health_check', '系统健康检查'), ('daily_summary', '每日汇总报告'), ('cleanup_old_tasks', '清理旧任务'), ('custom', '自定义任务')], max_length=50, verbose_name='任务类型')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('cron_expression', models.CharField(help_text='格式: 分 时 日 月 周', max_length=100, verbose_name='Cron表达式')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('last_run_status', models.CharField(blank=True, max_length=20, verbose_name='上次执行状态')),
                ('last_run_result', models.JSONField(blank=True, null=True, verbose_name='上次执行结果')),
                ('run_count', models.IntegerField(default=0, verbose_name='执行次数')),
                ('error_count', models.IntegerField(default=0, verbose_name='错误次数')),
                ('last_error', models.TextField(blank=True, verbose_name='上次错误信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('celery_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unified_schedules', to='django_celery_beat.periodictask', verbose_name='Celery定时任务')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '统一调度任务',
                'verbose_name_plural': '统一调度任务',
                'db_table': 'unified_schedules',
                'ordering': ['task_type', 'task_name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], default='running', max_length=20, verbose_name='状态')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='执行结果')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('duration', models.IntegerField(default=0, verbose_name='耗时(秒)')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='scheduler.unifiedschedule', verbose_name='调度任务')),
            ],
            options={
                'verbose_name': '调度执行日志',
                'verbose_name_plural': '调度执行日志',
                'db_table': 'schedule_execution_logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
