# Generated by Django 5.2.12 on 2026-03-18 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='会话ID')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '非活跃'), ('expired', '已过期')], default='active', max_length=20, verbose_name='状态')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='上下文数据')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Agent会话',
                'verbose_name_plural': 'Agent会话',
                'db_table': 'openclaw_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Agent ID')),
                ('agent_type', models.CharField(choices=[('collector', '采集Agent'), ('parser', '解析Agent'), ('generator', '生成Agent'), ('uploader', '上传Agent'), ('orchestrator', '编排Agent')], max_length=20, verbose_name='Agent类型')),
                ('status', models.CharField(choices=[('idle', '空闲'), ('running', '运行中'), ('paused', '暂停'), ('error', '错误'), ('stopped', '已停止')], default='idle', max_length=20, verbose_name='状态')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='上下文')),
                ('memory', models.JSONField(blank=True, default=dict, verbose_name='记忆')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_agents', to='openclaw.agentinstance', verbose_name='父Agent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='openclaw.agentsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': 'Agent实例',
                'verbose_name_plural': 'Agent实例',
                'db_table': 'openclaw_agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='任务ID')),
                ('task_type', models.CharField(max_length=50, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('input_data', models.JSONField(blank=True, default=dict, verbose_name='输入数据')),
                ('output_data', models.JSONField(blank=True, default=dict, verbose_name='输出数据')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('max_retries', models.IntegerField(default=3, verbose_name='最大重试次数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='openclaw.agentinstance', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Agent任务',
                'verbose_name_plural': 'Agent任务',
                'db_table': 'openclaw_tasks',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('provider', models.CharField(default='ollama', max_length=50, verbose_name='提供商')),
                ('prompt', models.TextField(verbose_name='提示词')),
                ('response', models.TextField(blank=True, verbose_name='响应')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='输入Token数')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='输出Token数')),
                ('temperature', models.FloatField(default=0.7, verbose_name='温度')),
                ('max_tokens', models.IntegerField(default=4096, verbose_name='最大Token数')),
                ('success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('execution_time', models.FloatField(default=0, verbose_name='执行时间(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_calls', to='openclaw.agentinstance', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'LLM调用记录',
                'verbose_name_plural': 'LLM调用记录',
                'db_table': 'openclaw_llm_calls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SandboxExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.CharField(db_index=True, max_length=64, verbose_name='单元ID')),
                ('code', models.TextField(verbose_name='执行代码')),
                ('output', models.TextField(blank=True, verbose_name='输出')),
                ('error', models.TextField(blank=True, verbose_name='错误')),
                ('success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('execution_time', models.FloatField(default=0, verbose_name='执行时间(秒)')),
                ('memory_used', models.IntegerField(default=0, verbose_name='内存使用(KB)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sandbox_executions', to='openclaw.agentinstance', verbose_name='Agent')),
            ],
            options={
                'verbose_name': '沙箱执行记录',
                'verbose_name_plural': '沙箱执行记录',
                'db_table': 'openclaw_sandbox_executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(db_index=True, max_length=100, verbose_name='技能名称')),
                ('skill_category', models.CharField(blank=True, max_length=50, verbose_name='技能分类')),
                ('success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('input_params', models.JSONField(blank=True, default=dict, verbose_name='输入参数')),
                ('output_data', models.JSONField(blank=True, default=dict, verbose_name='输出数据')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('execution_time', models.FloatField(default=0, verbose_name='执行时间(秒)')),
                ('memory_used', models.IntegerField(default=0, verbose_name='内存使用(KB)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_executions', to='openclaw.agentinstance', verbose_name='Agent')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_executions', to='openclaw.agentsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': '技能执行记录',
                'verbose_name_plural': '技能执行记录',
                'db_table': 'openclaw_skill_executions',
                'ordering': ['-created_at'],
            },
        ),
    ]
