# Generated by Django 5.2.12 on 2026-03-25 07:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openclaw', '0003_init_llm_providers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='默认配置', max_length=100, verbose_name='配置名称')),
                ('description', models.TextField(blank=True, verbose_name='配置描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '自动化配置',
                'verbose_name_plural': '自动化配置',
                'db_table': 'automation_configs',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='provider_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI'), ('anthropic', 'Anthropic Claude'), ('ollama', 'Ollama (本地)'), ('vllm', 'vLLM (本地)'), ('zhipu', '智谱AI'), ('qwen', '通义千问'), ('deepseek', 'DeepSeek'), ('moonshot', 'Moonshot'), ('minimax', 'MiniMax'), ('custom', '自定义')], max_length=20, verbose_name='提供商类型'),
        ),
        migrations.CreateModel(
            name='AutoMatchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AUTO_MATCH_ENABLED', models.BooleanField(default=True, verbose_name='启用自动匹配')),
                ('AUTO_IMPORT_THRESHOLD', models.FloatField(default=0.8, help_text='>=此相似度自动入库（无需确认）', verbose_name='自动入库阈值')),
                ('AUTO_BID_MATCH_THRESHOLD', models.FloatField(default=0.6, help_text='>=此相似度进行自动投标', verbose_name='自动投标匹配阈值')),
                ('EXCLUDE_THRESHOLD', models.FloatField(default=0.6, help_text='<此相似度自动排除', verbose_name='排除阈值')),
                ('ADAPTIVE_THRESHOLD', models.BooleanField(default=True, help_text='根据匹配质量自动优化阈值', verbose_name='自适应阈值调整')),
                ('LEARNING_FROM_HISTORY', models.BooleanField(default=True, help_text='根据中标/失标结果自动优化匹配策略', verbose_name='从历史结果学习')),
                ('KEYWORD_BOOST_ENABLED', models.BooleanField(default=True, help_text='匹配时对关键词命中进行加权', verbose_name='关键词加权')),
                ('REGION_BOOST_ENABLED', models.BooleanField(default=True, help_text='匹配时对地区进行加权', verbose_name='地区加权')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_configs', to='openclaw.automationconfig', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '自动匹配配置',
                'verbose_name_plural': '自动匹配配置',
                'db_table': 'auto_match_configs',
            },
        ),
        migrations.CreateModel(
            name='AIDecisionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUALIFICATION_WEIGHT', models.FloatField(default=0.4, verbose_name='资质匹配权重')),
                ('COMPETITOR_WEIGHT', models.FloatField(default=0.2, verbose_name='竞争对手分析权重')),
                ('PERFORMANCE_WEIGHT', models.FloatField(default=0.2, verbose_name='历史业绩匹配权重')),
                ('RISK_WEIGHT', models.FloatField(default=0.2, verbose_name='风险评估权重')),
                ('AUTO_BID_THRESHOLD', models.IntegerField(default=60, help_text='>=此分数自动投标', verbose_name='自动投标阈值')),
                ('OBSERVATION_THRESHOLD', models.IntegerField(default=40, help_text='>=此分数标记观察', verbose_name='观察阈值')),
                ('SKIP_THRESHOLD', models.IntegerField(default=40, help_text='<此分数自动跳过', verbose_name='跳过阈值')),
                ('USE_AI_DECISION', models.BooleanField(default=True, help_text='关闭则使用规则匹配', verbose_name='启用AI决策')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_configs', to='openclaw.automationconfig', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': 'AI决策配置',
                'verbose_name_plural': 'AI决策配置',
                'db_table': 'ai_decision_configs',
            },
        ),
        migrations.CreateModel(
            name='CrawlConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AUTO_LEARN_KEYWORDS', models.BooleanField(default=True, help_text='根据历史中标项目自动优化关键词', verbose_name='自动学习关键词')),
                ('ADAPTIVE_CRAWL_MODE', models.BooleanField(default=True, help_text='根据网站情况自动选择最优采集策略', verbose_name='自适应采集模式')),
                ('MULTI_SOURCE_ENABLED', models.BooleanField(default=True, help_text='是否启用多网站并行采集', verbose_name='多源采集')),
                ('DEFAULT_CRAWL_INTERVAL', models.IntegerField(default=60, help_text='定时采集的间隔时间', verbose_name='默认采集间隔(分钟)')),
                ('MAX_PAGES_PER_CRAWL', models.IntegerField(default=50, verbose_name='每次最大采集页数')),
                ('ENABLE_DEDUP', models.BooleanField(default=True, verbose_name='启用去重')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_configs', to='openclaw.automationconfig', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '采集配置',
                'verbose_name_plural': '采集配置',
                'db_table': 'crawl_configs',
            },
        ),
        migrations.CreateModel(
            name='DocumentReviewConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AUTO_UPLOAD_THRESHOLD', models.IntegerField(default=90, help_text='>=此分数自动上传标书', verbose_name='自动上传阈值')),
                ('OBSERVATION_THRESHOLD', models.IntegerField(default=60, help_text='>=此分数上传后标记观察', verbose_name='观察阈值')),
                ('MANUAL_REVIEW_THRESHOLD', models.IntegerField(default=60, help_text='<此分数触发人工审核', verbose_name='人工审核阈值')),
                ('MAX_OPTIMIZATION_ROUNDS', models.IntegerField(default=3, help_text='标书审核未通过时的最大自动优化次数', verbose_name='最大优化轮数')),
                ('ENABLE_ANTI_REJECTION_CHECK', models.BooleanField(default=True, help_text='自动检测可能导致废标的风险项', verbose_name='启用废标检查')),
                ('ENABLE_PRICE_ANALYSIS', models.BooleanField(default=True, help_text='分析报价合理性和竞争力', verbose_name='启用报价分析')),
                ('USE_SIMULATED_SCORING', models.BooleanField(default=True, help_text='模拟评委视角对标书进行打分', verbose_name='启用模拟打分')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_configs', to='openclaw.automationconfig', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '文档审核配置',
                'verbose_name_plural': '文档审核配置',
                'db_table': 'document_review_configs',
            },
        ),
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOTIFICATION_ENABLED', models.BooleanField(default=True, verbose_name='启用通知')),
                ('DINGTALK_ENABLED', models.BooleanField(default=True, verbose_name='钉钉通知')),
                ('KEY_EVENTS_ONLY', models.BooleanField(default=False, help_text='开启后仅对关键事件发送通知', verbose_name='仅关键事件')),
                ('DAILY_REPORT_ENABLED', models.BooleanField(default=True, verbose_name='日报')),
                ('WEEKLY_REPORT_ENABLED', models.BooleanField(default=False, verbose_name='周报')),
                ('NOTIFY_ON_START', models.BooleanField(default=False, verbose_name='启动通知')),
                ('NOTIFY_ON_SUCCESS', models.BooleanField(default=True, verbose_name='成功通知')),
                ('NOTIFY_ON_FAILURE', models.BooleanField(default=True, verbose_name='失败通知')),
                ('NOTIFY_ON_WIN', models.BooleanField(default=True, verbose_name='中标通知')),
                ('NOTIFY_ON_LOSS', models.BooleanField(default=True, verbose_name='失标通知')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_configs', to='openclaw.automationconfig', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '通知配置',
                'verbose_name_plural': '通知配置',
                'db_table': 'notification_configs',
            },
        ),
        migrations.CreateModel(
            name='RiskControlConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAX_DAILY_BIDS', models.IntegerField(default=50, help_text='超过此数量暂停当日自动投标', verbose_name='每日最大投标数')),
                ('AMOUNT_THRESHOLD', models.DecimalField(decimal_places=2, default=1000000, help_text='超过此金额的项目需人工确认', max_digits=15, verbose_name='金额阈值')),
                ('CONSECUTIVE_FAILURES', models.IntegerField(default=3, help_text='连续失败超过此次数自动暂停', verbose_name='连续失败上限')),
                ('ENABLE_AMOUNT_CHECK', models.BooleanField(default=True, verbose_name='启用金额检查')),
                ('ENABLE_COUNT_CHECK', models.BooleanField(default=True, verbose_name='启用数量检查')),
                ('ENABLE_FAILURE_CHECK', models.BooleanField(default=True, verbose_name='启用失败检查')),
                ('AUTO_PAUSE_ON_RISK', models.BooleanField(default=True, help_text='检测到风险时自动暂停相关任务', verbose_name='风险自动暂停')),
                ('NOTIFY_ON_RISK', models.BooleanField(default=True, help_text='检测到风险时发送钉钉通知', verbose_name='风险通知')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_configs', to='openclaw.automationconfig', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '风险控制配置',
                'verbose_name_plural': '风险控制配置',
                'db_table': 'risk_control_configs',
            },
        ),
    ]
