# Generated by Django 5.2.12 on 2026-03-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openclaw', '0004_add_automation_configs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='provider_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI'), ('anthropic', 'Anthropic Claude'), ('ollama', 'Ollama (本地)'), ('vllm', 'vLLM (本地)'), ('zhipu', '智谱AI'), ('qwen', '通义千问'), ('deepseek', 'DeepSeek'), ('kimi', 'Kimi (月之暗面)'), ('wenxin', '文心一言'), ('moonshot', 'Moonshot'), ('minimax', 'MiniMax'), ('custom', '自定义')], max_length=20, verbose_name='提供商类型'),
        ),
    ]
