# Generated by Django 4.2.16 on 2026-04-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openclaw', '0005_add_kimi_wenxin_providers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmprovider',
            name='api_key',
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='_api_key',
            field=models.TextField(blank=True, db_column='api_key', null=True, verbose_name='API密钥(加密)'),
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='FEISHU_ENABLED',
            field=models.BooleanField(default=False, verbose_name='飞书通知'),
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='MULTI_CHANNEL_ENABLED',
            field=models.BooleanField(default=False, help_text='开启后同一事件同时推送到所有已配置渠道', verbose_name='多渠道同步通知'),
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='WECOM_ENABLED',
            field=models.BooleanField(default=False, verbose_name='企业微信通知'),
        ),
    ]
