# Generated by Django 4.2.16 on 2026-04-15 05:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('openclaw', '0006_add_feedback_memory_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemoryStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, max_length=100, verbose_name='Agent ID')),
                ('agent_type', models.CharField(db_index=True, max_length=50, verbose_name='Agent类型')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='会话ID')),
                ('scope', models.CharField(choices=[('session', '会话级'), ('agent_type', 'Agent类型级'), ('enterprise', '企业级'), ('global', '全局')], default='session', max_length=20, verbose_name='记忆范围')),
                ('memory_key', models.CharField(db_index=True, max_length=200, verbose_name='记忆键')),
                ('memory_value', models.JSONField(default=dict, verbose_name='记忆值')),
                ('enterprise_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='企业ID')),
                ('access_count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='最后访问时间')),
                ('expires_at', models.DateTimeField(blank=True, help_text='为空则永不过期', null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Agent记忆存储',
                'verbose_name_plural': 'Agent记忆存储',
                'db_table': 'agent_memory_store',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BidFeedbackRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_id', models.IntegerField(verbose_name='招标项目ID')),
                ('enterprise_id', models.IntegerField(blank=True, null=True, verbose_name='企业ID')),
                ('workflow_id', models.IntegerField(blank=True, null=True, verbose_name='工作流ID')),
                ('bid_result', models.CharField(choices=[('won', '中标'), ('lost', '未中标'), ('rejected', '废标'), ('pending', '待定')], default='pending', max_length=20, verbose_name='投标结果')),
                ('overall_score', models.IntegerField(default=0, help_text='0-100', verbose_name='总体评分')),
                ('compliance_score', models.IntegerField(default=0, verbose_name='合规性评分')),
                ('completeness_score', models.IntegerField(default=0, verbose_name='完整性评分')),
                ('quality_score', models.IntegerField(default=0, verbose_name='质量评分')),
                ('competitiveness_score', models.IntegerField(default=0, verbose_name='竞争力评分')),
                ('weaknesses', models.JSONField(blank=True, default=list, verbose_name='待改进点')),
                ('suggestions', models.JSONField(blank=True, default=list, verbose_name='优化建议')),
                ('document_sections_summary', models.JSONField(blank=True, default=list, verbose_name='文档章节摘要')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='废标/被拒原因')),
                ('is_learned', models.BooleanField(default=False, help_text='是否已提取策略', verbose_name='是否已学习')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标书反馈记录',
                'verbose_name_plural': '标书反馈记录',
                'db_table': 'bid_feedback_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseBidExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_id', models.IntegerField(db_index=True, verbose_name='企业ID')),
                ('experience_type', models.CharField(choices=[('win_pattern', '中标模式'), ('loss_pattern', '失标模式'), ('strength', '企业优势'), ('weakness', '企业劣势'), ('pricing_strategy', '报价策略'), ('technical_preference', '技术偏好'), ('competitor_intel', '竞争对手情报'), ('region_preference', '区域偏好')], db_index=True, max_length=30, verbose_name='经验类型')),
                ('title', models.CharField(max_length=200, verbose_name='经验标题')),
                ('content', models.JSONField(default=dict, verbose_name='经验内容')),
                ('source_tender_id', models.IntegerField(blank=True, null=True, verbose_name='来源招标ID')),
                ('source_workflow_id', models.IntegerField(blank=True, null=True, verbose_name='来源工作流ID')),
                ('confidence', models.FloatField(default=0.5, help_text='0-1', verbose_name='置信度')),
                ('relevance_score', models.FloatField(default=0, help_text='0-100', verbose_name='相关性评分')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('is_verified', models.BooleanField(default=False, verbose_name='已验证')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '企业投标经验',
                'verbose_name_plural': '企业投标经验',
                'db_table': 'enterprise_bid_experiences',
                'ordering': ['-confidence', '-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='GenerationStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rejection_prevention', '废标预防'), ('quality_critical', '质量关键提升'), ('compliance_improvement', '合规性改进'), ('completeness_improvement', '完整性补全'), ('content_quality', '内容质量优化'), ('competitiveness_boost', '竞争力增强'), ('general_optimization', '通用优化')], db_index=True, max_length=50, verbose_name='策略分类')),
                ('name', models.CharField(max_length=200, verbose_name='策略名称')),
                ('description', models.TextField(blank=True, verbose_name='策略描述')),
                ('optimization_rules', models.JSONField(blank=True, default=list, help_text='提取的优化规则列表', verbose_name='优化规则')),
                ('feedback_count', models.IntegerField(default=0, verbose_name='反馈样本数')),
                ('average_score', models.FloatField(default=0, verbose_name='平均评分')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功次数')),
                ('failure_count', models.IntegerField(default=0, verbose_name='失败次数')),
                ('effectiveness_score', models.FloatField(default=0, help_text='0-100, 基于成功率', verbose_name='有效性评分')),
                ('last_feedback_at', models.DateTimeField(blank=True, null=True, verbose_name='最近反馈时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '生成策略',
                'verbose_name_plural': '生成策略',
                'db_table': 'generation_strategies',
                'ordering': ['-effectiveness_score', '-feedback_count'],
            },
        ),
        migrations.CreateModel(
            name='StrategyLearningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_type', models.CharField(choices=[('auto_extract', '自动提取'), ('manual_update', '手动更新'), ('batch_learning', '批量学习')], default='auto_extract', max_length=20, verbose_name='学习类型')),
                ('extracted_rules', models.JSONField(blank=True, default=list, verbose_name='提取的规则')),
                ('confidence', models.FloatField(default=0, help_text='0-1, 学习结果的置信度', verbose_name='置信度')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('feedback_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_logs', to='openclaw.bidfeedbackrecord', verbose_name='关联反馈记录')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_logs', to='openclaw.generationstrategy', verbose_name='关联策略')),
            ],
            options={
                'verbose_name': '策略学习日志',
                'verbose_name_plural': '策略学习日志',
                'db_table': 'strategy_learning_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='generationstrategy',
            index=models.Index(fields=['category', 'is_active'], name='generation__categor_64c6c1_idx'),
        ),
        migrations.AddIndex(
            model_name='generationstrategy',
            index=models.Index(fields=['effectiveness_score'], name='generation__effecti_2d8de3_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprisebidexperience',
            index=models.Index(fields=['enterprise_id', 'experience_type'], name='enterprise__enterpr_5e429b_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprisebidexperience',
            index=models.Index(fields=['confidence'], name='enterprise__confide_574d44_idx'),
        ),
        migrations.AddIndex(
            model_name='bidfeedbackrecord',
            index=models.Index(fields=['tender_id'], name='bid_feedbac_tender__ba43b6_idx'),
        ),
        migrations.AddIndex(
            model_name='bidfeedbackrecord',
            index=models.Index(fields=['bid_result', 'created_at'], name='bid_feedbac_bid_res_65bcbb_idx'),
        ),
        migrations.AddIndex(
            model_name='bidfeedbackrecord',
            index=models.Index(fields=['overall_score'], name='bid_feedbac_overall_169a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmemorystore',
            index=models.Index(fields=['agent_type', 'scope'], name='agent_memor_agent_t_7db49f_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmemorystore',
            index=models.Index(fields=['enterprise_id', 'agent_type'], name='agent_memor_enterpr_f9d2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmemorystore',
            index=models.Index(fields=['expires_at'], name='agent_memor_expires_b8beaf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentmemorystore',
            unique_together={('agent_type', 'scope', 'memory_key', 'enterprise_id')},
        ),
    ]
