# Generated by Django 4.2.16 on 2026-04-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openclaw', '0007_add_feedback_and_memory_tables'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agentmemorystore',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='agentmemorystore',
            constraint=models.UniqueConstraint(condition=models.Q(('enterprise_id__isnull', False)), fields=('agent_type', 'scope', 'memory_key', 'enterprise_id'), name='unique_agent_memory'),
        ),
        migrations.AddConstraint(
            model_name='agentmemorystore',
            constraint=models.UniqueConstraint(condition=models.Q(('enterprise_id__isnull', True)), fields=('agent_type', 'scope', 'memory_key'), name='unique_agent_memory_global'),
        ),
    ]
