# Generated by Django 5.2.12 on 2026-03-20 01:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_add_auto_bid_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='传真'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='auto_bid_threshold',
            field=models.IntegerField(default=60, help_text='推荐分数达到此阈值自动投标', verbose_name='自动投标阈值'),
        ),
        migrations.CreateModel(
            name='EnterpriseBidConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_consortium', models.BooleanField(default=True, verbose_name='是否接受联合体投标')),
                ('builder_level', models.CharField(blank=True, choices=[('first', '一级注册建造师'), ('second', '二级注册建造师'), ('none', '不作要求')], max_length=20, null=True, verbose_name='建造师等级')),
                ('builder_majors', models.JSONField(blank=True, default=list, verbose_name='建造师专业')),
                ('no_ongoing_project', models.BooleanField(default=False, verbose_name='是否要求无在建项目')),
                ('need_similar_performance', models.BooleanField(default=False, verbose_name='是否需要类似业绩')),
                ('similar_performance_desc', models.TextField(blank=True, null=True, verbose_name='类似业绩描述')),
                ('need_safety_certificate_b', models.BooleanField(default=True, verbose_name='是否需要安全生产考核合格证B证')),
                ('other_personnel_requirements', models.TextField(blank=True, null=True, verbose_name='其他人员要求')),
                ('need_safety_license', models.BooleanField(default=True, verbose_name='是否需要有效的安全生产许可证')),
                ('performance_years', models.IntegerField(blank=True, help_text='近X年内', null=True, verbose_name='业绩年限')),
                ('min_contract_amount', models.DecimalField(blank=True, decimal_places=2, help_text='万元', max_digits=15, null=True, verbose_name='最低合同金额')),
                ('min_building_area', models.DecimalField(blank=True, decimal_places=2, help_text='平方米', max_digits=12, null=True, verbose_name='最低建筑面积')),
                ('structure_types', models.JSONField(blank=True, default=list, verbose_name='结构类型')),
                ('other_performance_features', models.TextField(blank=True, null=True, verbose_name='其他业绩特征描述')),
                ('need_audit_report', models.BooleanField(default=True, verbose_name='是否需要近三年审计报告')),
                ('min_net_assets', models.DecimalField(blank=True, decimal_places=2, help_text='万元', max_digits=15, null=True, verbose_name='最低净资产要求')),
                ('max_debt_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='百分比', max_digits=5, null=True, verbose_name='资产负债率上限')),
                ('min_credit_line', models.DecimalField(blank=True, decimal_places=2, help_text='万元', max_digits=15, null=True, verbose_name='最低银行授信额度')),
                ('min_working_capital', models.DecimalField(blank=True, decimal_places=2, help_text='万元', max_digits=15, null=True, verbose_name='最低流动资金要求')),
                ('no_bad_credit', models.BooleanField(default=True, verbose_name='是否要求无不良信用记录')),
                ('no_bribery_record', models.BooleanField(default=True, verbose_name='是否要求无行贿犯罪记录')),
                ('not_in_blacklist', models.BooleanField(default=True, verbose_name='是否要求不在建筑市场黑名单')),
                ('other_reputation_requirements', models.TextField(blank=True, null=True, verbose_name='其他信誉要求')),
                ('min_registered_capital', models.DecimalField(blank=True, decimal_places=2, help_text='万元', max_digits=15, null=True, verbose_name='企业注册资金下限')),
                ('need_general_taxpayer', models.BooleanField(default=False, verbose_name='是否要求一般纳税人资格')),
                ('company_certifications', models.JSONField(blank=True, default=list, help_text='质量/环境/职业健康体系认证', verbose_name='体系认证')),
                ('equipment_requirements', models.TextField(blank=True, null=True, verbose_name='特定机械/设备要求')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid_config', to='enterprise.enterprise', verbose_name='企业')),
            ],
            options={
                'verbose_name': '企业投标配置',
                'verbose_name_plural': '企业投标配置',
                'db_table': 'enterprise_bid_configs',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('business_license', '营业执照'), ('qualification_cert', '资质证书'), ('safety_license', '安全生产许可证'), ('honor_cert', '荣誉证书'), ('contract', '合同复印件'), ('audit_report', '审计报告'), ('credit_report', '信用报告'), ('iso_cert', 'ISO认证证书'), ('tax_cert', '税务登记证'), ('org_code', '组织机构代码证'), ('bank_permit', '开户许可证'), ('legal_id', '法人身份证'), ('bid_bond', '投标保证金凭证'), ('performance_cert', '业绩证明材料'), ('personnel_cert', '人员资质证书'), ('equipment_cert', '设备证明材料'), ('other', '其他文档')], max_length=50, verbose_name='文档类型')),
                ('document_name', models.CharField(max_length=200, verbose_name='文档名称')),
                ('document_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='证书编号')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='发证日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有效期至')),
                ('issuing_authority', models.CharField(blank=True, max_length=200, null=True, verbose_name='发证机关')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='enterprise_docs/%Y/%m/', verbose_name='文档文件')),
                ('file_size', models.BigIntegerField(blank=True, help_text='字节', null=True, verbose_name='文件大小')),
                ('file_type', models.CharField(blank=True, help_text='MIME类型', max_length=50, null=True, verbose_name='文件类型')),
                ('status', models.CharField(choices=[('valid', '有效'), ('expiring', '即将过期'), ('expired', '已过期'), ('pending', '待审核')], default='valid', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主要文档')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否已验证')),
                ('remind_days', models.IntegerField(default=30, help_text='过期前多少天提醒', verbose_name='提前提醒天数')),
                ('last_remind_date', models.DateField(blank=True, null=True, verbose_name='上次提醒日期')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_enterprise_documents', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='enterprise.enterprise', verbose_name='企业')),
            ],
            options={
                'verbose_name': '企业文档',
                'verbose_name_plural': '企业文档',
                'db_table': 'enterprise_documents',
                'ordering': ['-is_primary', 'document_type', '-expiry_date'],
                'indexes': [models.Index(fields=['enterprise', 'document_type'], name='enterprise__enterpr_3ccf14_idx'), models.Index(fields=['status'], name='enterprise__status_074a00_idx'), models.Index(fields=['expiry_date'], name='enterprise__expiry__dd82e4_idx')],
            },
        ),
    ]
