# Generated by Django 5.2.12 on 2026-03-20 09:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_add_enterprise_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('upload', '上传'), ('download', '下载'), ('preview', '预览'), ('edit', '编辑'), ('delete', '删除'), ('recognize', '内容识别'), ('compare', '数据库比对'), ('update', '更新记录'), ('verify', '验证'), ('set_primary', '设为主要'), ('batch_delete', '批量删除')], max_length=20, verbose_name='操作类型')),
                ('action_detail', models.TextField(blank=True, null=True, verbose_name='操作详情')),
                ('old_data', models.JSONField(blank=True, default=dict, verbose_name='修改前数据')),
                ('new_data', models.JSONField(blank=True, default=dict, verbose_name='修改后数据')),
                ('recognition_result', models.JSONField(blank=True, default=dict, verbose_name='识别结果')),
                ('comparison_result', models.JSONField(blank=True, default=dict, verbose_name='比对结果')),
                ('update_result', models.JSONField(blank=True, default=dict, verbose_name='更新结果')),
                ('is_success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='用户代理')),
                ('operated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '证书审计日志',
                'verbose_name_plural': '证书审计日志',
                'db_table': 'document_audit_logs',
                'ordering': ['-operated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='enterprisedocument',
            options={'ordering': ['-is_primary', 'document_type', '-expiry_date'], 'verbose_name': '企业证书', 'verbose_name_plural': '企业证书'},
        ),
        migrations.AddField(
            model_name='enterprisedocument',
            name='comparison_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='比对时间'),
        ),
        migrations.AddField(
            model_name='enterprisedocument',
            name='comparison_result',
            field=models.JSONField(blank=True, default=dict, help_text='与数据库比对的结果', verbose_name='比对结果'),
        ),
        migrations.AddField(
            model_name='enterprisedocument',
            name='extracted_content',
            field=models.TextField(blank=True, help_text='OCR/文本提取的内容', null=True, verbose_name='提取内容'),
        ),
        migrations.AddField(
            model_name='enterprisedocument',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict, help_text='结构化提取数据', verbose_name='提取数据'),
        ),
        migrations.AddField(
            model_name='enterprisedocument',
            name='is_ai_reference',
            field=models.BooleanField(default=True, help_text='作为AI招标公告比对的参考数据', verbose_name='是否用于AI比对'),
        ),
        migrations.AddField(
            model_name='enterprisedocument',
            name='is_bid_material',
            field=models.BooleanField(default=True, help_text='作为标书生成的素材', verbose_name='是否用于标书生成'),
        ),
        migrations.AddField(
            model_name='enterprisedocument',
            name='recognition_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='识别时间'),
        ),
        migrations.AddField(
            model_name='enterprisedocument',
            name='recognition_error',
            field=models.TextField(blank=True, null=True, verbose_name='识别错误信息'),
        ),
        migrations.AddField(
            model_name='enterprisedocument',
            name='recognition_status',
            field=models.CharField(default='pending', help_text='pending: 待识别, processing: 识别中, completed: 已完成, failed: 识别失败', max_length=20, verbose_name='识别状态'),
        ),
        migrations.AlterField(
            model_name='enterprisedocument',
            name='document_name',
            field=models.CharField(max_length=200, verbose_name='证书名称'),
        ),
        migrations.AlterField(
            model_name='enterprisedocument',
            name='document_type',
            field=models.CharField(choices=[('business_license', '营业执照'), ('qualification_cert', '资质证书'), ('safety_license', '安全生产许可证'), ('honor_cert', '荣誉证书'), ('contract', '合同复印件'), ('audit_report', '审计报告'), ('credit_report', '信用报告'), ('iso_cert', 'ISO认证证书'), ('tax_cert', '税务登记证'), ('org_code', '组织机构代码证'), ('bank_permit', '开户许可证'), ('legal_id', '法人身份证'), ('bid_bond', '投标保证金凭证'), ('performance_cert', '业绩证明材料'), ('personnel_cert', '人员资质证书'), ('equipment_cert', '设备证明材料'), ('other', '其他证书')], max_length=50, verbose_name='证书类型'),
        ),
        migrations.AlterField(
            model_name='enterprisedocument',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='enterprise_docs/%Y/%m/', verbose_name='证书文件'),
        ),
        migrations.AlterField(
            model_name='enterprisedocument',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='是否主要证书'),
        ),
        migrations.AddIndex(
            model_name='enterprisedocument',
            index=models.Index(fields=['recognition_status'], name='enterprise__recogni_0bdc67_idx'),
        ),
        migrations.AddField(
            model_name='documentauditlog',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='enterprise.enterprisedocument', verbose_name='证书'),
        ),
        migrations.AddField(
            model_name='documentauditlog',
            name='operated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddIndex(
            model_name='documentauditlog',
            index=models.Index(fields=['document', 'action_type'], name='document_au_documen_3fb406_idx'),
        ),
        migrations.AddIndex(
            model_name='documentauditlog',
            index=models.Index(fields=['operated_at'], name='document_au_operate_d5186c_idx'),
        ),
    ]
