# Generated by Django 5.2.12 on 2026-03-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_documentauditlog_alter_enterprisedocument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='enterprise_type',
            field=models.CharField(blank=True, choices=[('limited', '有限责任公司'), ('joint_stock', '股份有限公司'), ('sole_proprietorship', '个人独资企业'), ('partnership', '合伙企业'), ('other', '其他')], max_length=25, null=True, verbose_name='企业类型'),
        ),
    ]
