# Generated by Django 5.2.12 on 2026-03-21 08:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_update_enterprise_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='enterprise_scale',
            field=models.CharField(blank=True, help_text='大型/中型/小型/微型', max_length=50, null=True, verbose_name='企业规模'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='industry_code',
            field=models.CharField(blank=True, help_text='国民经济行业分类代码', max_length=50, null=True, verbose_name='国标行业代码'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='insured_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='参保人数'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='staff_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='员工人数'),
        ),
        migrations.CreateModel(
            name='EnterpriseKeyPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_type', models.CharField(choices=[('technical_director', '技术负责人'), ('project_manager', '项目经理'), ('safety_officer', '安全员'), ('quality_inspector', '质检员'), ('other', '其他')], max_length=30, verbose_name='人员类型')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('id_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='身份证号')),
                ('certificate_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='证书名称')),
                ('certificate_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='证书类型')),
                ('certificate_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='证书等级')),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='证书编号')),
                ('certificate_major', models.CharField(blank=True, max_length=100, null=True, verbose_name='注册专业')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='发证日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有效期至')),
                ('issuing_authority', models.CharField(blank=True, max_length=200, null=True, verbose_name='发证机关')),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='注册编号')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='注册日期')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('certificate_status', models.CharField(choices=[('valid', '有效'), ('expired', '已过期'), ('expiring', '即将过期')], default='valid', max_length=20, verbose_name='证书状态')),
                ('is_available', models.BooleanField(default=True, help_text='是否可用于投标', verbose_name='是否可用')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_personnel', to='enterprise.enterprise', verbose_name='企业')),
            ],
            options={
                'verbose_name': '企业关键人员',
                'verbose_name_plural': '企业关键人员',
                'db_table': 'enterprise_key_personnel',
                'ordering': ['personnel_type', '-is_available', 'name'],
                'indexes': [models.Index(fields=['enterprise', 'personnel_type'], name='enterprise__enterpr_4235b2_idx'), models.Index(fields=['certificate_status'], name='enterprise__certifi_19ee4b_idx')],
            },
        ),
    ]
