# Generated by Django 5.2.12 on 2026-03-22 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0006_add_enterprise_fields_and_key_personnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='industry_code',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='website',
        ),
    ]
