# Generated by Django 5.2.12 on 2026-03-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0007_remove_unused_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprisekeypersonnel',
            name='certificate_level',
        ),
        migrations.RemoveField(
            model_name='enterprisekeypersonnel',
            name='certificate_name',
        ),
        migrations.RemoveField(
            model_name='enterprisekeypersonnel',
            name='certificate_type',
        ),
        migrations.RemoveField(
            model_name='enterprisekeypersonnel',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='enterprisekeypersonnel',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='enterprisekeypersonnel',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='enterprisekeypersonnel',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='出生年月'),
        ),
        migrations.AddField(
            model_name='enterprisekeypersonnel',
            name='builder_certificate',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='建造师证书'),
        ),
        migrations.AddField(
            model_name='enterprisekeypersonnel',
            name='engineer_title_certificate',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='工程师职称证'),
        ),
        migrations.AddField(
            model_name='enterprisekeypersonnel',
            name='is_registered_locally',
            field=models.BooleanField(default=True, help_text='用于系统自动比对住建部"四库一平台"数据', verbose_name='是否为本单位注册人员'),
        ),
        migrations.AddField(
            model_name='enterprisekeypersonnel',
            name='issuing_authority_full',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='发证单位全称'),
        ),
        migrations.AddField(
            model_name='enterprisekeypersonnel',
            name='labor_contract',
            field=models.FileField(blank=True, null=True, upload_to='personnel/contract/%Y/%m/', verbose_name='劳动合同'),
        ),
        migrations.AddField(
            model_name='enterprisekeypersonnel',
            name='no_ongoing_commitment',
            field=models.FileField(blank=True, null=True, upload_to='personnel/commitment/%Y/%m/', verbose_name='无在建承诺'),
        ),
        migrations.AddField(
            model_name='enterprisekeypersonnel',
            name='officer_type',
            field=models.CharField(blank=True, choices=[('construction', '施工员'), ('quality', '质量员'), ('safety', '安全员'), ('standard', '标准员'), ('material', '材料员'), ('machinery', '机械员'), ('labor', '劳务员'), ('data', '资料员')], max_length=20, null=True, verbose_name='八大员类型'),
        ),
        migrations.AddField(
            model_name='enterprisekeypersonnel',
            name='personnel_id',
            field=models.CharField(blank=True, help_text='系统自动生成的流水号或人员ID', max_length=50, null=True, unique=True, verbose_name='人员唯一标识'),
        ),
        migrations.AddField(
            model_name='enterprisekeypersonnel',
            name='professional_years',
            field=models.IntegerField(blank=True, help_text='用于量化打分（如：10年以上得满分）', null=True, verbose_name='从事本专业年限'),
        ),
        migrations.AddField(
            model_name='enterprisekeypersonnel',
            name='safety_certificate_b',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='安全生产考核合格证B证'),
        ),
        migrations.AddField(
            model_name='enterprisekeypersonnel',
            name='similar_performance_proof',
            field=models.FileField(blank=True, null=True, upload_to='personnel/performance/%Y/%m/', verbose_name='类似业绩证明'),
        ),
        migrations.AddField(
            model_name='enterprisekeypersonnel',
            name='social_security_code',
            field=models.CharField(blank=True, help_text='部分地区社保系统支持生成带有验证码的电子社保证明', max_length=50, null=True, verbose_name='社保验证码'),
        ),
        migrations.AddField(
            model_name='enterprisekeypersonnel',
            name='social_security_proof',
            field=models.FileField(blank=True, null=True, upload_to='personnel/social_security/%Y/%m/', verbose_name='社保缴纳证明'),
        ),
        migrations.AddField(
            model_name='enterprisekeypersonnel',
            name='title_level',
            field=models.CharField(blank=True, choices=[('senior', '高级'), ('intermediate', '中级'), ('junior', '初级'), ('assistant', '助理')], max_length=20, null=True, verbose_name='职称等级'),
        ),
        migrations.AlterField(
            model_name='enterprisekeypersonnel',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='证书有效期'),
        ),
        migrations.AlterField(
            model_name='enterprisekeypersonnel',
            name='personnel_type',
            field=models.CharField(choices=[('project_manager', '项目经理'), ('technical_director', '技术负责人'), ('professional_engineer', '专业工程师'), ('eight_officers', '八大员')], max_length=30, verbose_name='人员类型'),
        ),
        migrations.AddIndex(
            model_name='enterprisekeypersonnel',
            index=models.Index(fields=['personnel_id'], name='enterprise__personn_5c24a5_idx'),
        ),
    ]
