# Generated by Django 5.2.12 on 2026-03-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0008_update_key_personnel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisekeypersonnel',
            name='builder_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='personnel/builder_cert/%Y/%m/', verbose_name='建造师证书文件'),
        ),
        migrations.AddField(
            model_name='enterprisekeypersonnel',
            name='engineer_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='personnel/engineer_cert/%Y/%m/', verbose_name='工程师职称证文件'),
        ),
        migrations.AddField(
            model_name='enterprisekeypersonnel',
            name='safety_certificate_b_file',
            field=models.FileField(blank=True, null=True, upload_to='personnel/safety_cert/%Y/%m/', verbose_name='安全生产B证文件'),
        ),
    ]
