# Generated by Django 4.2.7 on 2026-03-22
# 为关键字段添加索引以优化查询性能

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    添加数据库索引迁移
    """

    dependencies = [
        ('enterprise', '0009_add_personnel_certificate_files'),
    ]

    operations = [
        # Enterprise 表索引
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['name'], name='enterprise_name_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['credit_code'], name='enterprise_credit_code_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['province', 'city'], name='enterprise_location_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['is_active', 'is_verified'], name='enterprise_status_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['created_at'], name='enterprise_created_idx'),
        ),
        
        # EnterpriseQualification 表索引
        migrations.AddIndex(
            model_name='enterprisequalification',
            index=models.Index(fields=['enterprise', 'expiry_date'], name='qualification_enterprise_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprisequalification',
            index=models.Index(fields=['qualification_type'], name='qualification_type_idx'),
        ),
        
        # EnterprisePerformance 表索引
        migrations.AddIndex(
            model_name='enterpriseperformance',
            index=models.Index(fields=['enterprise', 'project_name'], name='performance_enterprise_project_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriseperformance',
            index=models.Index(fields=['performance_type'], name='performance_type_idx'),
        ),
        
        # EnterpriseKeyPersonnel 表索引
        migrations.AddIndex(
            model_name='enterprisekeypersonnel',
            index=models.Index(fields=['enterprise', 'personnel_type'], name='personnel_enterprise_type_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprisekeypersonnel',
            index=models.Index(fields=['name'], name='personnel_name_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprisekeypersonnel',
            index=models.Index(fields=['expiry_date'], name='personnel_expiry_idx'),
        ),
        
        # EnterpriseDocument 表索引
        migrations.AddIndex(
            model_name='enterprisedocument',
            index=models.Index(fields=['enterprise', 'document_type'], name='document_enterprise_type_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprisedocument',
            index=models.Index(fields=['status'], name='document_status_idx'),
        ),
    ]
