# Generated by Django 5.2.12 on 2026-03-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0010_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='enterprise',
            name='enterprise_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='enterprise',
            name='enterprise_credit_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='enterprise',
            name='enterprise_location_idx',
        ),
        migrations.RemoveIndex(
            model_name='enterprise',
            name='enterprise_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='enterprise',
            name='enterprise_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='enterprisedocument',
            name='document_enterprise_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='enterprisedocument',
            name='document_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='enterprisekeypersonnel',
            name='personnel_enterprise_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='enterprisekeypersonnel',
            name='personnel_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='enterprisekeypersonnel',
            name='personnel_expiry_idx',
        ),
        migrations.RemoveIndex(
            model_name='enterpriseperformance',
            name='performance_enterprise_project_idx',
        ),
        migrations.RemoveIndex(
            model_name='enterpriseperformance',
            name='performance_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='enterprisequalification',
            name='qualification_enterprise_expiry_idx',
        ),
        migrations.RemoveIndex(
            model_name='enterprisequalification',
            name='qualification_type_idx',
        ),
        migrations.RemoveField(
            model_name='enterprisequalification',
            name='certificate_number',
        ),
        migrations.RemoveField(
            model_name='enterprisequalification',
            name='qualification_type',
        ),
        migrations.RemoveField(
            model_name='enterprisequalification',
            name='scope',
        ),
        migrations.AddField(
            model_name='enterprisequalification',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='资质证书号'),
        ),
        migrations.AddField(
            model_name='enterprisequalification',
            name='qualification_category',
            field=models.CharField(choices=[('survey', '工程勘察'), ('design', '工程设计'), ('construction', '建筑业企业'), ('supervision', '工程监理')], default='construction', max_length=50, verbose_name='资质类别'),
        ),
        migrations.AlterField(
            model_name='enterprisedocument',
            name='recognition_at',
            field=models.DateField(blank=True, null=True, verbose_name='识别时间'),
        ),
        migrations.AlterField(
            model_name='enterprisequalification',
            name='qualification_name',
            field=models.CharField(choices=[('building_construction', '建筑工程施工总承包'), ('municipal_engineering', '市政公用工程施工总承包'), ('mechanical_electrical', '机电工程施工总承包'), ('steel_structure', '钢结构工程专业承包'), ('foundation', '地基基础工程专业承包'), ('decoration', '建筑装修装饰工程专业承包'), ('curtain_wall', '建筑幕墙工程专业承包'), ('fire_protection', '消防设施工程专业承包'), ('waterproof_anticorrosion', '防水防腐保温工程专业承包'), ('environmental', '环保工程专业承包'), ('lighting', '城市及道路照明工程专业承包'), ('special', '特种工程专业承包')], max_length=50, verbose_name='资质名称'),
        ),
    ]
