# Generated by Django 5.2.12 on 2026-03-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0012_increase_id_number_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisekeypersonnel',
            name='id_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='身份证号'),
        ),
    ]
