# Generated by Django 4.2.16 on 2026-04-21 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0013_id_number_plaintext'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='enterprise',
            name='enterprises_name_fa29bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='enterprise',
            name='enterprises_credit__51c1de_idx',
        ),
        migrations.RemoveIndex(
            model_name='enterprisekeypersonnel',
            name='enterprise__personn_5c24a5_idx',
        ),
    ]
