# Generated by Django 4.2.7 on 2026-03-17 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300, verbose_name='公司名称')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司简称')),
                ('business_license', models.CharField(blank=True, max_length=100, null=True, verbose_name='营业执照号')),
                ('legal_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='法人代表')),
                ('registered_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='注册资本')),
                ('establish_date', models.DateField(blank=True, null=True, verbose_name='成立日期')),
                ('company_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司类型')),
                ('business_scope', models.TextField(blank=True, null=True, verbose_name='经营范围')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='公司地址')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='城市')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='区县')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系邮箱')),
                ('fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='传真')),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='开户银行')),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='银行账号')),
                ('qualifications', models.JSONField(blank=True, default=list, verbose_name='资质信息')),
                ('certifications', models.JSONField(blank=True, default=list, verbose_name='认证信息')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
                'db_table': 'company_infos',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('template_type', models.CharField(choices=[('bid_document', '投标文件'), ('business_license', '营业执照'), ('qualification', '资质证书'), ('authorization', '授权书'), ('proposal', '投标方案'), ('other', '其他')], default='bid_document', max_length=50, verbose_name='模板类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='模板描述')),
                ('file_path', models.FileField(upload_to='templates/%Y/%m/', verbose_name='模板文件')),
                ('variables', models.JSONField(blank=True, default=list, help_text='模板中可替换的变量列表', verbose_name='模板变量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文档模板',
                'verbose_name_plural': '文档模板',
                'db_table': 'document_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='文档名称')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='generated_docs/%Y/%m/', verbose_name='文档文件')),
                ('pdf_path', models.FileField(blank=True, null=True, upload_to='generated_pdfs/%Y/%m/', verbose_name='PDF文件')),
                ('variables_data', models.JSONField(blank=True, default=dict, verbose_name='变量数据')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('generated', '已生成'), ('reviewed', '已审核'), ('submitted', '已提交')], default='draft', max_length=20, verbose_name='状态')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '生成文档',
                'verbose_name_plural': '生成文档',
                'db_table': 'generated_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
