# Generated by Django 5.2.12 on 2026-03-18 12:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(max_length=300, verbose_name='企业名称')),
                ('qualification_types', models.JSONField(blank=True, default=list, help_text='企业拥有的资质类型', verbose_name='资质类型')),
                ('qualification_levels', models.JSONField(blank=True, default=list, help_text='企业拥有的资质等级', verbose_name='资质等级')),
                ('accept_consortium', models.BooleanField(default=True, verbose_name='是否接受联合体投标')),
                ('builder_level', models.CharField(blank=True, choices=[('first', '一级注册建造师'), ('second', '二级注册建造师'), ('none', '不作要求')], max_length=20, null=True, verbose_name='建造师等级')),
                ('builder_majors', models.JSONField(blank=True, default=list, help_text='建造师专业', verbose_name='建造师专业')),
                ('no_ongoing_project', models.BooleanField(default=False, verbose_name='是否要求无在建项目')),
                ('need_similar_performance', models.BooleanField(default=False, verbose_name='是否需要类似业绩')),
                ('similar_performance_desc', models.TextField(blank=True, null=True, verbose_name='类似业绩描述')),
                ('need_safety_certificate_b', models.BooleanField(default=True, verbose_name='是否需要安全生产考核合格证B证')),
                ('other_personnel_requirements', models.TextField(blank=True, null=True, verbose_name='其他人员要求')),
                ('need_safety_license', models.BooleanField(default=True, verbose_name='是否需要有效的安全生产许可证')),
                ('performance_years', models.IntegerField(blank=True, help_text='近X年内', null=True, verbose_name='业绩年限')),
                ('min_contract_amount', models.DecimalField(blank=True, decimal_places=2, help_text='万元', max_digits=15, null=True, verbose_name='最低合同金额')),
                ('min_building_area', models.DecimalField(blank=True, decimal_places=2, help_text='平方米', max_digits=12, null=True, verbose_name='最低建筑面积')),
                ('structure_types', models.JSONField(blank=True, default=list, verbose_name='结构类型')),
                ('other_performance_features', models.TextField(blank=True, null=True, verbose_name='其他业绩特征描述')),
                ('need_audit_report', models.BooleanField(default=True, verbose_name='是否需要近三年审计报告')),
                ('min_net_assets', models.DecimalField(blank=True, decimal_places=2, help_text='万元', max_digits=15, null=True, verbose_name='最低净资产要求')),
                ('max_debt_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='百分比', max_digits=5, null=True, verbose_name='资产负债率上限')),
                ('min_credit_line', models.DecimalField(blank=True, decimal_places=2, help_text='万元', max_digits=15, null=True, verbose_name='最低银行授信额度')),
                ('min_working_capital', models.DecimalField(blank=True, decimal_places=2, help_text='万元', max_digits=15, null=True, verbose_name='最低流动资金要求')),
                ('no_bad_credit', models.BooleanField(default=True, verbose_name='是否要求无不良信用记录')),
                ('no_bribery_record', models.BooleanField(default=True, verbose_name='是否要求无行贿犯罪记录')),
                ('not_in_blacklist', models.BooleanField(default=True, verbose_name='是否要求不在建筑市场黑名单')),
                ('other_reputation_requirements', models.TextField(blank=True, null=True, verbose_name='其他信誉要求')),
                ('min_registered_capital', models.DecimalField(blank=True, decimal_places=2, help_text='万元', max_digits=15, null=True, verbose_name='企业注册资金下限')),
                ('need_general_taxpayer', models.BooleanField(default=False, verbose_name='是否要求一般纳税人资格')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='质量/环境/职业健康体系认证', verbose_name='体系认证')),
                ('equipment_requirements', models.TextField(blank=True, null=True, verbose_name='特定机械/设备要求')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_qualifications', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '企业资质要求',
                'verbose_name_plural': '企业资质要求',
                'db_table': 'enterprise_qualification_requirements',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
