# Generated by Django 5.2.12 on 2026-03-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_enterprisequalification'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='accept_consortium',
            field=models.BooleanField(default=True, verbose_name='是否接受联合体投标'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='builder_level',
            field=models.CharField(blank=True, choices=[('first', '一级注册建造师'), ('second', '二级注册建造师'), ('none', '不作要求')], max_length=20, null=True, verbose_name='建造师等级'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='builder_majors',
            field=models.JSONField(blank=True, default=list, help_text='建造师专业', verbose_name='建造师专业'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='company_certifications',
            field=models.JSONField(blank=True, default=list, help_text='质量/环境/职业健康体系认证', verbose_name='体系认证'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='equipment_requirements',
            field=models.TextField(blank=True, null=True, verbose_name='特定机械/设备要求'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='max_debt_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='百分比', max_digits=5, null=True, verbose_name='资产负债率上限'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='min_building_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='平方米', max_digits=12, null=True, verbose_name='最低建筑面积'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='min_contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='万元', max_digits=15, null=True, verbose_name='最低合同金额'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='min_credit_line',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='万元', max_digits=15, null=True, verbose_name='最低银行授信额度'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='min_net_assets',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='万元', max_digits=15, null=True, verbose_name='最低净资产要求'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='min_registered_capital',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='万元', max_digits=15, null=True, verbose_name='企业注册资金下限'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='min_working_capital',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='万元', max_digits=15, null=True, verbose_name='最低流动资金要求'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='need_audit_report',
            field=models.BooleanField(default=True, verbose_name='是否需要近三年审计报告'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='need_general_taxpayer',
            field=models.BooleanField(default=False, verbose_name='是否要求一般纳税人资格'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='need_safety_certificate_b',
            field=models.BooleanField(default=True, verbose_name='是否需要安全生产考核合格证B证'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='need_safety_license',
            field=models.BooleanField(default=True, verbose_name='是否需要有效的安全生产许可证'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='need_similar_performance',
            field=models.BooleanField(default=False, verbose_name='是否需要类似业绩'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='no_bad_credit',
            field=models.BooleanField(default=True, verbose_name='是否要求无不良信用记录'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='no_bribery_record',
            field=models.BooleanField(default=True, verbose_name='是否要求无行贿犯罪记录'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='no_ongoing_project',
            field=models.BooleanField(default=False, verbose_name='是否要求无在建项目'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='not_in_blacklist',
            field=models.BooleanField(default=True, verbose_name='是否要求不在建筑市场黑名单'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='other_performance_features',
            field=models.TextField(blank=True, null=True, verbose_name='其他业绩特征描述'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='other_personnel_requirements',
            field=models.TextField(blank=True, null=True, verbose_name='其他人员要求'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='other_reputation_requirements',
            field=models.TextField(blank=True, null=True, verbose_name='其他信誉要求'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='performance_years',
            field=models.IntegerField(blank=True, help_text='近X年内', null=True, verbose_name='业绩年限'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='qualification_levels',
            field=models.JSONField(blank=True, default=list, help_text='企业拥有的资质等级', verbose_name='资质等级'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='qualification_types',
            field=models.JSONField(blank=True, default=list, help_text='企业拥有的资质类型', verbose_name='资质类型'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='similar_performance_desc',
            field=models.TextField(blank=True, null=True, verbose_name='类似业绩描述'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='structure_types',
            field=models.JSONField(blank=True, default=list, verbose_name='结构类型'),
        ),
        migrations.DeleteModel(
            name='EnterpriseQualification',
        ),
    ]
