# Generated by Django 5.2.12 on 2026-03-18 13:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_companyinfo_accept_consortium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='tech_manager_certificate_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='技术负责人证书编号'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tech_manager_certificate_valid_date',
            field=models.DateField(blank=True, null=True, verbose_name='技术负责人证书有效期'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tech_manager_education',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='技术负责人学历'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tech_manager_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='技术负责人邮箱'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tech_manager_id_card',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='技术负责人身份证号'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tech_manager_major',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='技术负责人专业'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tech_manager_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='技术负责人姓名'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tech_manager_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='技术负责人电话'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tech_manager_resume',
            field=models.TextField(blank=True, null=True, verbose_name='技术负责人简历'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tech_manager_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='技术负责人职称'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tech_manager_work_years',
            field=models.IntegerField(blank=True, null=True, verbose_name='技术负责人工作年限'),
        ),
        migrations.CreateModel(
            name='CompanyCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('business_license', '营业执照'), ('qualification', '资质证书'), ('safety_license', '安全生产许可证'), ('iso9001', 'ISO9001质量管理体系认证'), ('iso14001', 'ISO14001环境管理体系认证'), ('iso45001', 'ISO45001职业健康安全管理体系认证'), ('credit_rating', '信用等级证书'), ('bank_credit', '银行授信证明'), ('audit_report', '审计报告'), ('tax_certificate', '纳税证明'), ('social_security', '社保证明'), ('honor_certificate', '荣誉证书'), ('tech_manager_cert', '技术负责人证书'), ('builder_cert', '建造师证书'), ('safety_cert_b', '安全生产考核合格证B证'), ('other', '其他证书')], max_length=50, verbose_name='证书类型')),
                ('certificate_name', models.CharField(max_length=200, verbose_name='证书名称')),
                ('certificate_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='证书编号')),
                ('issuing_authority', models.CharField(blank=True, max_length=200, null=True, verbose_name='发证机关')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='发证日期')),
                ('valid_start_date', models.DateField(blank=True, null=True, verbose_name='有效期开始')),
                ('valid_end_date', models.DateField(blank=True, null=True, verbose_name='有效期结束')),
                ('file_path', models.FileField(upload_to='certificates/%Y/%m/', verbose_name='证书文件')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='文件名称')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='文件大小')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='documents.companyinfo', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '公司证书',
                'verbose_name_plural': '公司证书',
                'db_table': 'company_certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('project_contract', '工程合同'), ('purchase_contract', '采购合同'), ('service_contract', '服务合同'), ('labor_contract', '劳动合同'), ('lease_contract', '租赁合同'), ('cooperation_contract', '合作协议'), ('sales_contract', '销售合同'), ('other', '其他合同')], max_length=50, verbose_name='合同类型')),
                ('contract_name', models.CharField(max_length=200, verbose_name='合同名称')),
                ('contract_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='合同编号')),
                ('party_a', models.CharField(blank=True, max_length=200, null=True, verbose_name='甲方')),
                ('party_b', models.CharField(blank=True, max_length=200, null=True, verbose_name='乙方')),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, help_text='万元', max_digits=15, null=True, verbose_name='合同金额')),
                ('project_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='项目名称')),
                ('project_location', models.CharField(blank=True, max_length=500, null=True, verbose_name='项目地点')),
                ('project_scale', models.CharField(blank=True, max_length=200, null=True, verbose_name='项目规模')),
                ('sign_date', models.DateField(blank=True, null=True, verbose_name='签订日期')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('file_path', models.FileField(upload_to='contracts/%Y/%m/', verbose_name='合同文件')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='文件名称')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='文件大小')),
                ('status', models.CharField(choices=[('valid', '有效'), ('expired', '已过期'), ('terminated', '已终止')], default='valid', max_length=20, verbose_name='状态')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='documents.companyinfo', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '公司合同',
                'verbose_name_plural': '公司合同',
                'db_table': 'company_contracts',
                'ordering': ['-created_at'],
            },
        ),
    ]
