# Generated by Django 5.2.12 on 2026-03-20 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_companyinfo_tech_manager_certificate_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontract',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='tech_manager_certificate_no',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='tech_manager_certificate_valid_date',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='tech_manager_education',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='tech_manager_email',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='tech_manager_id_card',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='tech_manager_major',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='tech_manager_name',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='tech_manager_phone',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='tech_manager_resume',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='tech_manager_title',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='tech_manager_work_years',
        ),
        migrations.DeleteModel(
            name='CompanyCertificate',
        ),
        migrations.DeleteModel(
            name='CompanyContract',
        ),
    ]
