# Generated by Django 5.2.12 on 2026-03-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_companyinfo_qualifications_list'),
        ('vectorlib', '0002_add_reference_docs_to_generated_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='ai_suggestions',
            field=models.JSONField(blank=True, default=dict, help_text='基于参考文档生成的AI建议内容', verbose_name='AI建议'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='reference_docs',
            field=models.ManyToManyField(blank=True, help_text='从向量库引用的参考文档', related_name='referenced_by', to='vectorlib.biddocumentlibrary', verbose_name='参考文档'),
        ),
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
    ]
