# Generated by Django 4.2.7 on 2026-03-17 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='投标编号')),
                ('bid_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='投标报价')),
                ('bid_date', models.DateField(blank=True, null=True, verbose_name='投标日期')),
                ('status', models.CharField(choices=[('preparing', '准备中'), ('submitted', '已提交'), ('reviewing', '评审中'), ('won', '已中标'), ('lost', '未中标'), ('withdrawn', '已撤回')], default='preparing', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('win_probability', models.IntegerField(blank=True, help_text='0-100之间的整数', null=True, verbose_name='中标概率')),
                ('competitor_count', models.IntegerField(blank=True, null=True, verbose_name='竞争对手数量')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '投标记录',
                'verbose_name_plural': '投标记录',
                'db_table': 'bid_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('win', '中标'), ('lose', '未中标'), ('pending', '待定')], default='pending', max_length=20, verbose_name='结果类型')),
                ('winner_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='中标单位')),
                ('winner_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='中标金额')),
                ('our_rank', models.IntegerField(blank=True, null=True, verbose_name='我方排名')),
                ('total_bidders', models.IntegerField(blank=True, null=True, verbose_name='投标单位数量')),
                ('announce_date', models.DateField(blank=True, null=True, verbose_name='公告日期')),
                ('announce_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='公告链接')),
                ('win_reason', models.TextField(blank=True, null=True, verbose_name='中标原因')),
                ('lose_reason', models.TextField(blank=True, null=True, verbose_name='未中标原因')),
                ('lessons_learned', models.TextField(blank=True, null=True, verbose_name='经验教训')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '中标结果',
                'verbose_name_plural': '中标结果',
                'db_table': 'bid_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bids', models.IntegerField(default=0, verbose_name='总投标次数')),
                ('won_bids', models.IntegerField(default=0, verbose_name='中标次数')),
                ('lost_bids', models.IntegerField(default=0, verbose_name='未中标次数')),
                ('pending_bids', models.IntegerField(default=0, verbose_name='待定次数')),
                ('total_bid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='总投标金额')),
                ('total_win_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='总中标金额')),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='中标率')),
                ('year', models.IntegerField(default=2026, verbose_name='统计年份')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='统计月份')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '投标统计',
                'verbose_name_plural': '投标统计',
                'db_table': 'bid_statistics',
                'ordering': ['-year', '-month'],
            },
        ),
    ]
