# Generated by Django 4.2.7 on 2026-03-17 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenders', '0001_initial'),
        ('bids', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidstatistics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid_statistics', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='bidresult',
            name='bid_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='bids.bidrecord', verbose_name='投标记录'),
        ),
        migrations.AddField(
            model_name='bidrecord',
            name='bid_documents',
            field=models.ManyToManyField(blank=True, related_name='bid_records', to='documents.generateddocument', verbose_name='投标文件'),
        ),
        migrations.AddField(
            model_name='bidrecord',
            name='bid_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_bids', to=settings.AUTH_USER_MODEL, verbose_name='投标负责人'),
        ),
        migrations.AddField(
            model_name='bidrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bid_records', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='bidrecord',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='participated_bids', to=settings.AUTH_USER_MODEL, verbose_name='团队成员'),
        ),
        migrations.AddField(
            model_name='bidrecord',
            name='tender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid_record', to='tenders.tenderproject', verbose_name='招标项目'),
        ),
    ]
