# Generated by Django 4.2.16 on 2026-04-14 03:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidrecord',
            name='bid_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='投标报价'),
        ),
        migrations.AlterField(
            model_name='bidrecord',
            name='competitor_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='竞争对手数量'),
        ),
        migrations.AlterField(
            model_name='bidrecord',
            name='win_probability',
            field=models.IntegerField(blank=True, help_text='0-100之间的整数', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='中标概率'),
        ),
        migrations.AlterField(
            model_name='bidresult',
            name='our_rank',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='我方排名'),
        ),
        migrations.AlterField(
            model_name='bidresult',
            name='total_bidders',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='投标单位数量'),
        ),
        migrations.AlterField(
            model_name='bidresult',
            name='winner_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='中标金额'),
        ),
    ]
