# Generated by Django 4.2.16 on 2026-04-15 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bids', '0003_alter_bidrecord_bid_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidstatistics',
            name='year',
            field=models.IntegerField(verbose_name='统计年份'),
        ),
        migrations.AlterUniqueTogether(
            name='bidstatistics',
            unique_together={('user', 'year', 'month')},
        ),
    ]
