# Generated by Django 4.2.7 on 2026-03-17 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('task_type', models.CharField(default='crawl_tenders', max_length=50, verbose_name='任务类型')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='任务参数')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '执行失败')], default='pending', max_length=20, verbose_name='任务状态')),
                ('result_count', models.IntegerField(default=0, verbose_name='结果数量')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '爬虫任务',
                'verbose_name_plural': '爬虫任务',
                'db_table': 'crawler_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('notice', '招标公告'), ('document', '招标文件'), ('clarification', '澄清文件'), ('result', '中标公告'), ('other', '其他')], default='document', max_length=20, verbose_name='文件类型')),
                ('file_name', models.CharField(max_length=500, verbose_name='文件名称')),
                ('file_path', models.FileField(upload_to='tender_files/%Y/%m/', verbose_name='文件路径')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小')),
                ('file_ext', models.CharField(blank=True, max_length=20, null=True, verbose_name='文件扩展名')),
                ('download_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='下载链接')),
                ('is_downloaded', models.BooleanField(default=False, verbose_name='是否已下载')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '招标文件',
                'verbose_name_plural': '招标文件',
                'db_table': 'tender_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True, verbose_name='关键词')),
                ('category', models.CharField(choices=[('industry', '行业关键词'), ('region', '地区关键词'), ('product', '产品关键词'), ('exclude', '排除关键词')], default='industry', max_length=20, verbose_name='关键词类别')),
                ('weight', models.IntegerField(default=1, verbose_name='权重')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '招标关键词',
                'verbose_name_plural': '招标关键词',
                'db_table': 'tender_keywords',
                'ordering': ['-weight', 'keyword'],
            },
        ),
        migrations.CreateModel(
            name='TenderProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='项目标题')),
                ('project_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目编号')),
                ('source_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='来源链接')),
                ('publish_date', models.DateField(db_index=True, verbose_name='发布日期')),
                ('deadline_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('open_date', models.DateField(blank=True, null=True, verbose_name='开标日期')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='地区')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='行业')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='类别')),
                ('purchaser_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='采购人名称')),
                ('purchaser_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='采购人联系人')),
                ('purchaser_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='采购人电话')),
                ('agency_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='代理机构名称')),
                ('agency_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='代理机构联系人')),
                ('agency_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='代理机构电话')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='预算金额')),
                ('description', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='技术要求')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('submitted', '已投标'), ('won', '已中标'), ('lost', '未中标'), ('expired', '已过期')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('keywords_matched', models.JSONField(blank=True, default=list, verbose_name='匹配关键词')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '招标项目',
                'verbose_name_plural': '招标项目',
                'db_table': 'tender_projects',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='来源名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='来源编码')),
                ('source_type', models.CharField(choices=[('government', '政府采购网'), ('enterprise', '企业招标平台'), ('other', '其他平台')], default='government', max_length=20, verbose_name='来源类型')),
                ('base_url', models.URLField(max_length=500, verbose_name='基础URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('crawler_config', models.JSONField(blank=True, default=dict, verbose_name='爬虫配置')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '招标来源',
                'verbose_name_plural': '招标来源',
                'db_table': 'tender_sources',
                'ordering': ['-created_at'],
            },
        ),
    ]
