# Generated by Django 4.2.7 on 2026-03-17 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderproject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenders', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='tenderproject',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='tenders.tendersource', verbose_name='信息来源'),
        ),
        migrations.AddField(
            model_name='tenderkeyword',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='tenderfile',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tenders.tenderproject', verbose_name='招标项目'),
        ),
        migrations.AddField(
            model_name='crawlertask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='crawlertask',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawler_tasks', to='tenders.tendersource', verbose_name='数据来源'),
        ),
        migrations.AddIndex(
            model_name='tenderproject',
            index=models.Index(fields=['status', 'publish_date'], name='tender_proj_status_174594_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderproject',
            index=models.Index(fields=['region', 'industry'], name='tender_proj_region_ba0cc5_idx'),
        ),
    ]
