# Generated by Django 4.2.16 on 2026-04-14 03:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_add_gin_fulltext_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderproject',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='crawlertask',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawler_tasks', to='tenders.tendersource', verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='crawlertask',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '执行失败')], db_index=True, default='pending', max_length=20, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='tenderfile',
            name='tender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='tenders.tenderproject', verbose_name='招标项目'),
        ),
        migrations.AlterField(
            model_name='tenderproject',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='预算金额'),
        ),
        migrations.AlterField(
            model_name='tenderproject',
            name='source_url',
            field=models.URLField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='来源链接'),
        ),
        migrations.AddIndex(
            model_name='crawlertask',
            index=models.Index(fields=['status', 'created_at'], name='crawler_tas_status_95e745_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderproject',
            index=models.Index(fields=['is_favorite', 'publish_date'], name='tender_proj_is_favo_c4b7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderproject',
            index=models.Index(fields=['is_read', 'publish_date'], name='tender_proj_is_read_3a3331_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderproject',
            index=models.Index(fields=['created_at'], name='tender_proj_created_f45f94_idx'),
        ),
    ]
