# Generated by Django 4.2.16 on 2026-04-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('action', models.CharField(blank=True, default='', max_length=200)),
                ('resource_type', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('risk_level', models.CharField(db_index=True, default='info', max_length=20)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='core_auditl_event_t_dff433_idx'), models.Index(fields=['user_id', '-created_at'], name='core_auditl_user_id_969660_idx'), models.Index(fields=['risk_level', '-created_at'], name='core_auditl_risk_le_a50b7f_idx')],
            },
        ),
    ]
