# Generated by Django 4.2.16 on 2026-04-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
